#FROM jkremser/mini-jre:8.1
FROM anapsix/alpine-java:8u202b08_jdk

ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -XshowSettings:vm"

COPY  /build/libs/micronaut-app-0.1-all.jar /quotes-app.jar

EXPOSE 8080

ENTRYPOINT ["/opt/jdk/bin/java", "-jar", "/quotes-app.jar"]