apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: quotes-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quotes-app
    spec:
      containers:
      - name: graal-app
        image: jkremser/micronaut-graal-app:native
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-app
spec:
  selector:
    app.kubernetes.io/name: quotes-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort #or LoadBalancer
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: quotes-app
# spec:
#   backend:
#     serviceName: quotes-app
#     servicePort: 8080